require("mason-lspconfig").setup({
    ensure_installed = {
    -- "sumneko_lua",
    -- "tsserver",
    -- "tailwindcss",
    -- "phpactor",
    -- "intelephense",
    -- "perInavigator",
    -- "vimls",
    -- "emmet_language_server",
    -- "emmet_ls",
    -- "eslint",
    -- "psalm",
    -- "nixd",
    -- "pyright",
    -- "cssls",
    -- "cssmodules_ls",
    -- "unocss","dockerls", "docker_compose_language_service", "ltex", "texlab", "lua_ls", "nil_ls",
    -- "rnix",
    -- "custom-elements-languageserver",
    -- "html-lsp",
    -- "markuplint",
    -- "prettier",
    -- "prettierd",
    -- "rome",
    -- "rustywind",
    -- "sonarlint-language-server",
  }
})
